---
- name: Set LVM configuration
  vars:
    lvm_snapshots_new_lvm_config: >
      {{ lvm_snapshots_snapshot_autoextend_percent is defined |
      ternary('activation/snapshot_autoextend_percent={{ lvm_snapshots_snapshot_autoextend_percent }}', '') }}
      {{ lvm_snapshots_snapshot_autoextend_threshold is defined |
      ternary('activation/snapshot_autoextend_threshold={{ lvm_snapshots_snapshot_autoextend_threshold }}', '') }}
  ansible.builtin.command: 'lvmconfig --mergedconfig --config "{{ lvm_snapshots_new_lvm_config }}" --file /etc/lvm/lvm.conf'
  changed_when: true
  when: ((lvm_snapshots_new_lvm_config | trim) | length) > 0

- name: Create snapshots
  community.general.lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    snapshot: "{{ item.lv }}_{{ lvm_snapshots_set_name }}"
    size: "{{ item.size | default(omit) }}"
  loop: "{{ lvm_snapshots_volumes }}"

- name: Create boot backup
  community.general.archive:
    format: gz
    mode: '0644'
    dest: "/root/boot-backup-{{ lvm_snapshots_set_name }}.tgz"
    path:
    - "/boot/initramfs-{{ ansible_kernel }}.img"
    - "/boot/vmlinuz-{{ ansible_kernel }}"
    - "/boot/System.map-{{ ansible_kernel }}"
    - "/boot/symvers-{{ ansible_kernel }}.gz"
    - "/boot/config-{{ ansible_kernel }}"
    - /boot/grub/grub.conf
    - /boot/grub2/grub.cfg
    - /boot/efi/EFI/redhat/grub.cfg
  when: lvm_snapshots_boot_backup
...
